import { chromium } from 'playwright';
import fs from 'node:fs';
const OUT='/tmp/claude-0/-home-user-Nadja-Makoie/cb853670-03ec-5223-b944-f49d62372839/scratchpad';
function fc(){const r=fs.readdirSync('/opt/pw-browsers').filter(d=>d.startsWith('chromium'));for(const x of r)for(const p of [`/opt/pw-browsers/${x}/chrome-linux/chrome`,`/opt/pw-browsers/${x}/chrome-linux/headless_shell`])if(fs.existsSync(p))return p;}
const errors=[];
const b=await chromium.launch({executablePath:fc()});
const c=await b.newContext({viewport:{width:1440,height:900}});
const tmp=await c.newPage();
const tile=await tmp.evaluate(()=>{const cv=document.createElement('canvas');cv.width=1200;cv.height=900;const x=cv.getContext('2d');const g=x.createLinearGradient(0,0,1200,900);g.addColorStop(0,'#8fbfe8');g.addColorStop(1,'#17324e');x.fillStyle=g;x.fillRect(0,0,1200,900);return cv.toDataURL('image/png');});
await tmp.close();
const buf=Buffer.from(tile.split(',')[1],'base64');
await c.route('**/images.higgs.ai/**',r=>r.fulfill({status:200,contentType:'image/png',body:buf}));
const p=await c.newPage();
p.on('pageerror',e=>errors.push('PAGEERROR: '+e.message));
await p.goto('http://localhost:4173/',{waitUntil:'networkidle'}).catch(()=>{});
await p.waitForTimeout(1000);
const hasIframe=await p.evaluate(()=>!!document.querySelector('#kontakt iframe'));
const hasExtImg=await p.evaluate(()=>!!document.querySelector('#kontakt img'));
await p.locator('#warum').scrollIntoViewIfNeeded();
await p.waitForTimeout(500);
await p.screenshot({path:`${OUT}/trans-why.png`});
await p.locator('#kontakt').scrollIntoViewIfNeeded();
await p.waitForTimeout(500);
await p.screenshot({path:`${OUT}/contact-new.png`});
const ofw=await p.evaluate(()=>document.documentElement.scrollWidth-document.documentElement.clientWidth);
const mob=await b.newContext({viewport:{width:390,height:844},deviceScaleFactor:2,isMobile:true});
await mob.route('**/images.higgs.ai/**',r=>r.fulfill({status:200,contentType:'image/png',body:buf}));
const mp=await mob.newPage();
await mp.goto('http://localhost:4173/',{waitUntil:'networkidle'}).catch(()=>{});
await mp.waitForTimeout(900);
const ofm=await mp.evaluate(()=>document.documentElement.scrollWidth-document.documentElement.clientWidth);
console.log('kontakt iframe (want false):',hasIframe,'| kontakt img (want true):',hasExtImg);
console.log('overflow desktop/mobile:',ofw,'/',ofm);
console.log('errors:',errors.length?errors:'none');
await b.close();
